name: Build Backend Container

on:
  push:
    branches:
      - main
    paths:
      - 'coneflip-backend/**'


  workflow_dispatch:
  
jobs:
  packer_build:
    runs-on: ubuntu-latest
    steps:

      - name: Add Packer key
        run: curl -fsSL https://apt.releases.hashicorp.com/gpg | sudo apt-key add -

      - name: Add Packer repo
        run: sudo apt-add-repository "deb [arch=amd64] https://apt.releases.hashicorp.com $(lsb_release -cs) main"

      - name: Install Packer
        run: sudo apt-get update && sudo apt-get install packer

      - uses: actions/checkout@v1

      - name: Build DotNet app
        run: mkdir -p output  && dotnet build coneflip-backend/coneflip-backend.csproj -o output/
      
      - name: Packer build
        run: cd .build && packer build coneflip-backend.pkr.hcl
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-west-1